# stage 1
# Use Node.js 18 as the base image for building the frontend
FROM node:18 As builder

# Set the working directory inside the container
WORKDIR /App

# Copy package.json and package-lock.json first
COPY package*.json ./

# npm install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the frontend app
RUN npm run build

# stage 2

# Use a lightweight Nginx server
FROM nginx:alpine

# Remove the default Nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy built frontend files from the previous stage
COPY --from=builder /app/build /usr/share/nginx/html

# expose 80 container port
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]

